@extends('layouts.app')

@section('content')
<div class="d-flex justify-content-center py-3">
    <div id="receipt" class="bg-white p-2" style="width:50mm; padding:6px;">
        <div class="text-center" style="font-family: 'Courier New', Courier, monospace;">
            {{-- Header logos: if you have logo files place them in public/img and name appropriately --}}
            <div style="display:flex;justify-content:center;align-items:center;gap:4px;margin-bottom:4px;flex-wrap:wrap;">
                @if(file_exists(public_path('img/company-logo-left.png')))
                    <img src="{{ asset('img/company-logo-left.png') }}" alt="logo" style="max-width:50px;">
                @else
                    <div style="font-weight:bold; font-size:calc(11px * var(--receipt-font-scale,1));">{{ strtoupper(config('app.name')) }}</div>
                @endif
                @if(file_exists(public_path('img/company-logo-right.png')))
                    <img src="{{ asset('img/company-logo-right.png') }}" alt="logo" style="max-width:50px;">
                @endif
            </div>

            {{-- Company info: prefer $company variable if controller passes it --}}
            <div style="font-size:calc(10px * var(--receipt-font-scale,1)); line-height:1.1;">
                <div>{{ $company['name'] ?? config('app.name') }}</div>
                @if(!empty($company['address']))
                    @foreach(explode("\n", $company['address']) as $line)
                        <div>{{ $line }}</div>
                    @endforeach
                @else
                    <div>Direccion de la empresa</div>
                    <div>CP: ----- COL. -----</div>
                @endif
                @if(!empty($company['rfc']))<div>R.F.C. {{ $company['rfc'] }}</div>@endif
                @if(!empty($company['phone']))<div>TEL: {{ $company['phone'] }}</div>@endif
            </div>

            <hr style="border:none;border-top:1px dashed #000;margin:8px 0;">

            <div style="text-align:left;font-size:calc(11px * var(--receipt-font-scale,1));margin-bottom:6px;">
                <div>Folio: {{ $sale->id }}</div>
                <div>Orden: #{{ $sale->orderID }}</div>
                <div>Fecha: {{ $sale->order_date }}</div>
                <div>Cliente: {{ $sale->nombre ?? 'N/D' }} {{ $sale->cedula ? ' / ' . $sale->cedula : '' }}</div>
            </div>

            <div style="width:100%;font-size:calc(11px * var(--receipt-font-scale,1));">
                @php
                    $rate = \App\Models\ExchangeRate::forDate($sale->order_date ?? now()->toDateString());
                    if(!$rate){
                        $rate = \App\Models\ExchangeRate::orderBy('date','desc')->value('rate');
                    }
                    // fallback to 1 so we always display a Bs amount (avoid showing USD)
                    $rate = $rate ? (float)$rate : 1.0;
                @endphp
                @foreach($items as $it)
                    @php
                        $qty = intval($it['quantity'] ?? 0);
                        $price = floatval($it['price'] ?? 0);
                        $lineTotal = $qty * $price;
                        $lineTotalBs = $lineTotal * $rate;
                        $name = $it['menuItemName'] ?? ($it['name'] ?? 'Item');
                    @endphp
                    <div class="receipt-line">
                        <div class="receipt-name">{{ Str::limit($name, 28) }}</div>
                        <div class="receipt-qty">{{ $qty }}</div>
                        <div class="receipt-price">{{ number_format($lineTotalBs,2) }} Bs</div>
                    </div>
                @endforeach
            </div>

            <hr style="border:none;border-top:1px dashed #000;margin:6px 0;">

            <div style="font-size:calc(11px * var(--receipt-font-scale,1));">
                @php
                    // Prefer stored total_bs if available, otherwise compute from USD fields using rate (which defaults to 1)
                    if(isset($sale->total_bs) && $sale->total_bs !== null){
                        $bsVal = (float)$sale->total_bs;
                    } else {
                        $usdVal = $sale->total_usd ?? $sale->total ?? 0;
                        $bsVal = $usdVal * $rate;
                    }
                @endphp
                <div style="display:flex;justify-content:space-between;font-weight:bold;margin-top:6px;"><div>TOTAL</div><div>{{ number_format($bsVal,2) }} Bs</div></div>
            </div>

            <div style="margin-top:8px;font-size:calc(10px * var(--receipt-font-scale,1));">
                <div>Pago: {{ $sale->payment_method ?? 'EFECTIVO' }}</div>
            </div>

            <div style="margin-top:10px; text-align:center;">
                {{-- Barcode area: generated by JsBarcode below using orderID or sale id --}}
                <svg id="barcode"></svg>
                <div style="font-size:10px;margin-top:6px;">{{ $sale->orderID }}</div>
            </div>

            <div style="margin-top:10px;font-size:calc(9px * var(--receipt-font-scale,1));line-height:1.2;">
                <div style="text-align:center;">CUENTANOS COMO TE ATENDIMOS INGRESANDO A</div>
                <div style="text-align:center;font-weight:bold;">www.aarfigo.com</div>
                <div style="height:8px;"></div>
                <div style="text-align:center;">GRACIAS POR SU COMPRA</div>
            </div>
        </div>

        <div class="text-center mt-2">
            <button id="print-btn" class="btn btn-dark btn-sm">Imprimir</button>
            <a href="{{ route('admin.cleaned-orders.show',$sale->id) }}" class="btn btn-dark btn-sm ms-2">Volver</a>
        </div>
    </div>
</div>
@endsection

@push('styles')
<style>
/* Receipt print styles */
body { background:#f7f7f7; }
#receipt { font-family: 'Courier New', Courier, monospace; color:#000; }
#receipt hr { margin:6px 0 }

/* Layout for product lines */
.receipt-line{ display:flex; align-items:center; justify-content:space-between; padding:4px 0; }
.receipt-name{ width:46%; min-width:0; overflow:hidden; text-overflow:ellipsis; white-space:nowrap; font-weight:600; font-size:calc(10px * var(--receipt-font-scale,1) * 1.04); }
.receipt-qty{ width:10%; min-width:0; text-align:center; font-size:calc(10px * var(--receipt-font-scale,1)); }
.receipt-price{ width:44%; min-width:0; text-align:right; white-space:nowrap; font-weight:600; font-size:calc(10px * var(--receipt-font-scale,1) * 1.04); }

.receipt-total-row{ display:flex; justify-content:space-between; font-weight:700; padding-top:6px; font-size:calc(11px * var(--receipt-font-scale,1) * 1.05); }

@media print {
    /* Force page size for ticket printers (attempt to set default paper size to 50mm) */
    @page { size: 50mm auto; margin: 0; }
    html, body { width: 50mm !important; height: auto !important; margin: 0 !important; padding: 0 !important; }
    body * { visibility: hidden; }
    #receipt, #receipt * { visibility: visible; }
    #receipt { position: absolute; left: 0; top: 0; width: 50mm !important; max-width: 50mm !important; box-sizing: border-box; margin:0; padding:2mm; }
    /* hide controls when printing */
    #print-btn, a.btn { display:none !important; }
}

/* Small-screen view: center the receipt */
@media (max-width:900px) {
    #receipt { box-shadow:none; border:none; }
}
</style>
@endpush

@push('scripts')
<!-- JsBarcode CDN for barcode generation -->
<script src="https://cdn.jsdelivr.net/npm/jsbarcode@3.11.5/dist/JsBarcode.all.min.js"></script>
<script>
// Helper to read query params
function getQueryParam(name) {
    var results = new RegExp('[?&]' + name + '=([^&#]*)').exec(window.location.search);
    return results ? decodeURIComponent(results[1].replace(/\+/g, ' ')) : null;
}

// Print helper: open a new window with only the receipt HTML and print that window.
// Print helper: print only the `#receipt` element by using a hidden iframe (avoids popup blockers).
function printReceipt() {
    var receipt = document.getElementById('receipt');
    if (!receipt) { window.print(); return; }

    // Clone the receipt so we keep the page intact
    var clone = receipt.cloneNode(true);

    // determine receipt width in mm (fallback to 50)
    var widthAttr = receipt.style.width || getComputedStyle(receipt).width || '50mm';
    var mm = 50;
    if (typeof widthAttr === 'string') {
        if (widthAttr.indexOf('mm') !== -1) {
            mm = parseInt(widthAttr);
        } else if (widthAttr.indexOf('px') !== -1) {
            var px = parseFloat(widthAttr);
            if (!isNaN(px)) mm = Math.round(px / 3.7795275591);
        }
    }

    // Build minimal HTML for the receipt
    var styles = '';
    styles += 'html,body{width:' + mm + 'mm !important;height:auto !important;margin:0;padding:0;background:#fff;font-family:"Courier New",Courier,monospace;color:#000}';
    styles += '@page{size:' + mm + 'mm auto;margin:0}';
    styles += '#receipt{width:' + mm + 'mm !important;max-width:' + mm + 'mm !important;box-sizing:border-box;margin:0;padding:0}';
    styles += '.receipt-line{display:flex;align-items:center;justify-content:space-between;padding:4px 0}';
    styles += '.receipt-name{width:46%;min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font-weight:600;font-size:calc(10px)}';
    styles += '.receipt-qty{width:10%;min-width:0;text-align:center;font-size:10px}';
    styles += '.receipt-price{width:44%;text-align:right;white-space:nowrap;font-weight:600;font-size:calc(10px)}';
    styles += '#print-btn,.btn{display:none !important}';
    styles += '@media print{body{margin:0;padding:0}}';

    var html = '<!doctype html><html><head><meta charset="utf-8"><title>Imprimir</title><style>' + styles + '</style></head><body>' + clone.innerHTML + '</body></html>';

    // Create a hidden iframe to host the receipt and trigger print (less likely to be blocked)
    try {
        var iframe = document.createElement('iframe');
        iframe.style.position = 'absolute';
        iframe.style.left = '-9999px';
        iframe.style.top = '0';
        iframe.style.width = mm + 'mm';
        iframe.style.height = 'auto';
        iframe.setAttribute('sandbox', 'allow-modals allow-same-origin');
        document.body.appendChild(iframe);

        var idoc = iframe.contentWindow || iframe.contentDocument;
        if (idoc.document) idoc = idoc.document;
        idoc.open();
        idoc.write(html);
        idoc.close();

        // Give browser a moment to render SVG/barcode and fonts
        setTimeout(function(){
            try {
                iframe.contentWindow.focus();
                // Print the iframe contents only
                iframe.contentWindow.print();
            } catch(e) {
                console.warn('Iframe print failed, falling back to popup print', e);
                // Fallback: open popup window with receipt (may be blocked)
                var w = window.open('', '_blank');
                if (w) { w.document.open(); w.document.write(html); w.document.close(); w.focus(); w.print(); }
                else { // last resort: print whole page
                    window.print();
                }
            }

            // Remove iframe after a short delay
            setTimeout(function(){
                try { document.body.removeChild(iframe); } catch(_){}
            }, 600);
        }, 300);
    } catch(e) {
        console.warn('printReceipt error', e);
        // If any unexpected error, fallback to printing the whole window
        window.print();
    }
}

// Re-add click listener for the print button (only present on screen). The print CSS hides the buttons during printing.
var _printBtn = document.getElementById('print-btn');
if(_printBtn){
    _printBtn.addEventListener('click', function(){
        try{
            printReceipt();
        }catch(e){
            // fallback to opening autoprint route if something fails
            try{ var url = window.location.href.split('?')[0] + '?autoprint=1&w=50'; window.open(url, '_blank', 'noopener'); }catch(_){ window.print(); }
        }
    });
}

window.addEventListener('DOMContentLoaded', function(){
    // allow ?width=50 or ?width=80 (in mm) to adapt the receipt for different printers
    var w = parseInt(getQueryParam('width')) || parseInt(getQueryParam('w')) || 50; // default 50mm (narrow receipt)
    if (isNaN(w) || w <= 0) w = 50;
    var receipt = document.getElementById('receipt');
    if (receipt) {
        // set physical width in mm for accurate printer rendering
        receipt.style.width = w + 'mm';
        // scale font sizes proportionally to a 50mm baseline
        var scale = (w / 50);
        document.documentElement.style.setProperty('--receipt-font-scale', scale);
    }

    // generate barcode using orderID if available, else sale id
    var code = String({{ json_encode($sale->orderID ?? $sale->id) }});
    try {
        var bw = (w && parseInt(w) <= 50) ? 1.4 : 2;
        var bh = (w && parseInt(w) <= 50) ? 36 : 50;
        JsBarcode('#barcode', code, {format: 'CODE128', width: bw, height: bh, displayValue:false, margin:2});
    } catch(e) {
        console.warn('JsBarcode failed', e);
    }

    if (window.location.search.indexOf('autoprint=1') !== -1) {
        setTimeout(function(){ window.print(); }, 250);
    }
});
</script>
@endpush
